title: LTEC 5210
description: >
  Instructional Systems Design I
permalink: /:year/:month/:day/:title/
baseurl: ""
url: "https://LTEC5210.ray.pillers.us"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Raymond Piller
author-img: //static.vertigion.com/images/Avatar-Negative.png
about-author: BS BCIS<br />I've been an I.T. Administrator for 18 years; I started out in the Army. Working on my MS and then PhD in <a href="http://lt.unt.edu" target="_blank">LTEC</a>.
social-twitter: VertigoRay
social-facebook: VertigoRay
social-github: VertigoRay
social-linkedin: VertigoRay
social-blog: 'http://blog.vertigion.com'
social-email: Raymond.Piller@my.unt.edu

# Disqus
discus-identifier: vertigoray

# Tracker
analytics: UA-20345769-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-gist

paginate: 8
paginate_path: "/page/:num"

# gist:
#   noscript: false

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
